sudo: false
language: rust

rust:
    - nightly
    - beta
    - stable

env:
  -
  - NO_STD=1

matrix:
  allow_failures:
    - rust: nightly
      env:
  exclude:
    - rust: beta
      env: NO_STD=1
    - rust: stable
      env: NO_STD=1

script:
  - ./ci/build.sh
  - ./ci/test.sh

