sudo: false
language: rust
matrix:
  include:
    - rust: nightly
      env: TEST_SUITE=suite_nightly
    - rust: beta
      env: TEST_SUITE=suite_beta
    - rust: stable
      env: TEST_SUITE=suite_stable
  allow_failures:
    - rust: nightly
    - rust: beta
script:
  - cargo build --verbose
  - cargo test --verbose;
  - cargo run --example vectors;
