[package]
name = "algebra"
version = "0.1.0"
authors = ["Brendan Zabarauskas"]

[lib]
name = "algebra"

[dev_dependencies.quickcheck]
git = "https://github.com/BurntSushi/quickcheck"

[dev_dependencies.quickcheck_macros]
git = "https://github.com/BurntSushi/quickcheck"
